### ISSUE TITLE
How to build/test?

### ISSUE THREAD

**Issue by twitchyliquid64** [dizzyliam/tree-sitter-muon#1] opened 2019-04-19 17:11 UTC
Heya,

Could you throw up some instructions for running this? I'm unfamiliar with node & however the C binding is compiled.

**Comment by dizzyliam** [comment] 2019-04-19 19:53
Yeah I probably should have my problem as an issue here. Since I'm lazy and haven't done a .gitignore, you can run `node_modules/tree-sitter-cli/tree-sitter generate` to build the parser after making any edits to the grammar.js, and you can run `node_modules/tree-sitter-cli/tree-sitter parse test.mu` to test it.

At the moment, when you run the generate command it will complain about some conflict that, as far as I can tell, shouldn't even be possible.

**Comment by dizzyliam** [comment] 2019-04-19 21:03
The problem is fixed now. I'll close this issue and add the information on how to test it to the readme. Expect to see any future problems appear as issues :)

**Closed by dizzyliam** 2019-04-19 21:03 UTC
